import { GoalItem, HouseholdFinancialProfile } from '../../types/goalPlanning';

export const DEMO_PROFILE: HouseholdFinancialProfile = {
  monthlyNetIncome: 75000,
  essentialMonthlyExpenses: 35000,
  discretionaryMonthlyExpenses: 0,
  existingCashBalance: 150000,
  protectedEmergencyReserve: 200000,
  unassignedSavings: 0,
  activeEmiMonthlyTotal: 8000,
  recurringBillsTotal: 0
};

export const DEMO_GOALS: GoalItem[] = [
  {
    id: 101,
    name: 'Emergency Reserve',
    emoji: '🛡️',
    targetAmount: 200000,
    currentAmount: 60000,
    targetDate: 'Dec 2027', // 14 months -> ₹10,000/mo
    category: 'Emergency',
    isFamilyGoal: true,
    priority: 1,
    priorityLabel: 'CRITICAL',
    goalType: 'EMERGENCY',
    hardDeadline: true,
    targetAmountLocked: true,
    deadlineFlexibilityMonths: 0,
    minimumAcceptableAmount: 180000,
    monthlyAllocation: 10000,
    monthlyContribution: 10000,
    expectedAnnualReturn: 0,
    inflationRate: 0,
    riskTolerance: 'LOW',
    essentiality: 'ESSENTIAL',
    canPause: false,
    canReduceTarget: false,
    currentStatus: 'ON_TRACK',
    status: 'ON_TRACK',
    familyMemberOwner: 'Family Shared'
  },
  {
    id: 102,
    name: 'House Down Payment',
    emoji: '🏡',
    targetAmount: 1000000,
    currentAmount: 100000,
    targetDate: 'Dec 2030', // 50 months -> ₹18,000/mo
    category: 'Home',
    isFamilyGoal: true,
    priority: 2,
    priorityLabel: 'HIGH',
    goalType: 'HOME',
    hardDeadline: false,
    targetAmountLocked: false,
    deadlineFlexibilityMonths: 24,
    minimumAcceptableAmount: 850000,
    monthlyAllocation: 12000,
    monthlyContribution: 12000,
    expectedAnnualReturn: 0,
    inflationRate: 0,
    riskTolerance: 'MEDIUM',
    essentiality: 'IMPORTANT',
    canPause: false,
    canReduceTarget: true,
    currentStatus: 'AT_RISK',
    status: 'AT_RISK',
    familyMemberOwner: 'Priyanshu & Priya'
  },
  {
    id: 103,
    name: 'Child Higher Education',
    emoji: '🎓',
    targetAmount: 500000,
    currentAmount: 0,
    targetDate: 'Jul 2029', // 33 months -> ~₹15,150/mo
    category: 'Education',
    isFamilyGoal: true,
    priority: 2,
    priorityLabel: 'HIGH',
    goalType: 'EDUCATION',
    hardDeadline: true,
    targetAmountLocked: true,
    deadlineFlexibilityMonths: 0,
    minimumAcceptableAmount: 450000,
    monthlyAllocation: 8000,
    monthlyContribution: 8000,
    expectedAnnualReturn: 0,
    inflationRate: 0,
    riskTolerance: 'LOW',
    essentiality: 'ESSENTIAL',
    canPause: false,
    canReduceTarget: false,
    currentStatus: 'CONFLICT',
    status: 'CONFLICTED',
    familyMemberOwner: 'Aarav (Son)'
  },
  {
    id: 104,
    name: 'Retirement Wealth Corpus',
    emoji: '🌱',
    targetAmount: 2000000,
    currentAmount: 350000,
    targetDate: 'Dec 2040', // 170 months -> ~₹9,700/mo
    category: 'Retirement',
    isFamilyGoal: true,
    priority: 3,
    priorityLabel: 'MEDIUM',
    goalType: 'RETIREMENT',
    hardDeadline: false,
    targetAmountLocked: false,
    deadlineFlexibilityMonths: 36,
    minimumAcceptableAmount: 1500000,
    monthlyAllocation: 2000,
    monthlyContribution: 2000,
    expectedAnnualReturn: 0,
    inflationRate: 0,
    riskTolerance: 'MEDIUM',
    essentiality: 'IMPORTANT',
    canPause: true,
    canReduceTarget: true,
    currentStatus: 'AT_RISK',
    status: 'AT_RISK',
    familyMemberOwner: 'Family Vault'
  },
  {
    id: 105,
    name: 'Family Vacation',
    emoji: '✈️',
    targetAmount: 150000,
    currentAmount: 30000,
    targetDate: 'Oct 2028', // 24 months -> ₹5,000/mo
    category: 'Travel',
    isFamilyGoal: true,
    priority: 4,
    priorityLabel: 'LOW',
    goalType: 'TRAVEL',
    hardDeadline: false,
    targetAmountLocked: false,
    deadlineFlexibilityMonths: 12,
    minimumAcceptableAmount: 100000,
    monthlyAllocation: 0,
    monthlyContribution: 0,
    expectedAnnualReturn: 0,
    inflationRate: 0,
    riskTolerance: 'HIGH',
    essentiality: 'OPTIONAL',
    canPause: true,
    canReduceTarget: true,
    currentStatus: 'AT_RISK',
    status: 'AT_RISK',
    familyMemberOwner: 'Family Shared'
  }
];
